#!/usr/bin/env python2.7
#/*+
#************************************************************************
#****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#*
#* (c) 2003.                (c) 2003.
#* National Research Council        Conseil national de recherches
#* Ottawa, Canada, K1A 0R6         Ottawa, Canada, K1A 0R6
#* All rights reserved            Tous droits reserves
#*                     
#* NRC disclaims any warranties,    Le CNRC denie toute garantie
#* expressed, implied, or statu-    enoncee, implicite ou legale,
#* tory, of any kind with respect    de quelque nature que se soit,
#* to the software, including        concernant le logiciel, y com-
#* without limitation any war-        pris sans restriction toute
#* ranty of merchantability or        garantie de valeur marchande
#* fitness for a particular pur-    ou de pertinence pour un usage
#* pose.  NRC shall not be liable    particulier.  Le CNRC ne
#* in any event for any damages,    pourra en aucun cas etre tenu
#* whether direct or indirect,        responsable de tout dommage,
#* special or general, consequen-    direct ou indirect, particul-
#* tial or incidental, arising        ier ou general, accessoire ou
#* from the use of the software.    fortuit, resultant de l'utili-
#*                     sation du logiciel.
#*
#************************************************************************
#*
#*   Script Name:    jcmt2mon
#*
#*   Purpose:
#*    Counts number of correct CAOM-2 observations, planes, artifacts, etc.
#*
#*   usage: jcmt2mon [options]
#*   
#*   options:
#*     -h, --help              show this help message and exit
#*     -D, --DEVSYBASE          
#*     -d DAY, --day=DAY       DAY  <  19800000 means days before today, \
#*                             DAY > 19800000 means UT date YYYYMMMDD
#*     -w WEEK, --week=WEEK    WEEK <  19800000 means weeks before now, \
#*                             WEEK > 19800000 means week containing UT date
#*                             Weeks run Sunday-Saturday
#*     -l PATH, --logdir PATH  path from . to store log files. \
#*                             if not specified, logs will not be stored.
#*
#*   Programmer        : Russell O. Redman
#*
#*   Modification History:
#*
#****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#************************************************************************
#-*/

from jcmt2caom2.mon import mon
from tools4caom2.logger import logger

thismon = mon()
thismon.run()
