#!/usr/bin/env python2.7
#/*+
#************************************************************************
#****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#*
#* (c) <year>.                (c) <year>.
#* National Research Council        Conseil national de recherches
#* Ottawa, Canada, K1A 0R6         Ottawa, Canada, K1A 0R6
#* All rights reserved            Tous droits reserves
#*
#* NRC disclaims any warranties,    Le CNRC denie toute garantie
#* expressed, implied, or statu-    enoncee, implicite ou legale,
#* tory, of any kind with respect    de quelque nature que se soit,
#* to the software, including        concernant le logiciel, y com-
#* without limitation any war-        pris sans restriction toute
#* ranty of merchantability or        garantie de valeur marchande
#* fitness for a particular pur-    ou de pertinence pour un usage
#* pose.  NRC shall not be liable    particulier.  Le CNRC ne
#* in any event for any damages,    pourra en aucun cas etre tenu
#* whether direct or indirect,        responsable de tout dommage,
#* special or general, consequen-    direct ou indirect, particul-
#* tial or incidental, arising        ier ou general, accessoire ou
#* from the use of the software.    fortuit, resultant de l'utili-
#*                     sation du logiciel.
#*
#************************************************************************
#*
#*   Script Name:    jcmt2caom2raw
#*
#*   Purpose:
#*    Ingest jcmt raw ACSIS and SCUBA-2 data into CAOM 2.0
#*
#*   Functions:
#+    function_name    : Brief description
#+    function_name    : Brief description
#*    ...
#*
#*   Field
#*    $Revision: 9 $
#*    $Date: 2009-12-10 13:12:37 -0800 (Thu, 10 Dec 2009) $
#*    $Author: redman $
#*
#*
#*   Modification History:
#*
#****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#************************************************************************
#-*/

from jcmt2caom2.raw import raw
from tools4caom2.logger import logger

myraw = raw()
myraw.parse_command_line()
myraw.setup_logger()
myraw.run()
