#!/usr/bin/env python2.7

import logging

from tools4caom2.util import configure_logger

from jcmt2caom2.jcmt2caom2ingest import jcmt2caom2ingest

configure_logger(level=logging.INFO)

myingest = jcmt2caom2ingest()
myingest.run()
