#!/usr/bin/env python3

import logging
import sys

from tools4caom2.util import configure_logger

from jcmt2caom2.jcmt2caom2ingest import jcmt2caom2ingest

configure_logger(level=logging.INFO)

myingest = jcmt2caom2ingest()
if not myingest.run():
    sys.exit(1)
