#!/usr/bin/env python3

import logging
import sys

from tools4caom2.util import configure_logger

from jcmt2caom2.reduced import reduced

configure_logger(level=logging.INFO)

myingest = reduced()
if not myingest.run():
    sys.exit(1)
