#!/usr/bin/env python3

import logging
import sys

from tools4caom2.util import configure_logger

from jcmt2caom2.raw import raw

configure_logger(level=logging.INFO)

myraw = raw()
if not myraw.run():
    sys.exit(1)
