#!/usr/bin/env python2.7

import logging

from tools4caom2.util import configure_logger

from jcmt2caom2.setfield import setfield

configure_logger(level=logging.INFO)

mysetfield = setfield()
mysetfield.run()
