#!/usr/bin/env python2.7

import logging
import sys

from tools4caom2.util import configure_logger

from jcmt2caom2.setfield import setfield

configure_logger(level=logging.INFO)

mysetfield = setfield()
if not mysetfield.run():
    sys.exit(1)
